export const screens = {
  login: 'login',
  signUp: 'signup',
  auth: 'auth',
  main: 'main',
  home: 'home',
  tabs: 'tabs',
  topTabs: 'top-tabs',
  screenNav: 'screen-nav',
  profile: 'profile',
  users: 'users',
  forYou: 'forYou',
  following: 'following',
  newPost: 'new-post',
};
